### ISSUE TITLE
System.InvalidCastException for NET8

### ISSUE THREAD

**Issue by RoccoZero** [amerkoleci/Vortice.Win32#3]
07:35:41 | ERROR | System.InvalidCastException: Unable to cast object of type 'Win32.Graphics.Direct2D.AffineTransform2DProperties' to type 'System.UInt32'.
   at Win32.Graphics.Direct2D.ID2D1PropertiesExtensions.SetValue[TD2D1Properties,T,U](TD2D1Properties& self, U index, T* value) in D:\a\Vortice.Win32\Vortice.Win32\src\Vortice.Win32.Graphics.Direct2D\ID2D1Properties.cs:line 59
   
   
<img width="676" alt="image" src="https://github.com/amerkoleci/Vortice.Win32/assets/33149580/9de15193-447a-4123-9115-838a8c7b3cf0">

**Comment by amerkoleci** [comment]
Version 2.1.0 fixes this issue.
Thanks for reporting

**Comment by RoccoZero** [comment]
I keep getting this error on Version 2.1.0

```
23:33:12 | ERROR | System.InvalidCastException: Unable to cast object of type 'Win32.Graphics.Direct2D.AffineTransform2DProperties' to type 'System.UInt32'.
   at Win32.Graphics.Direct2D.ID2D1PropertiesExtensions.SetValue[TD2D1Properties,T,U](TD2D1Properties& self, U index, T* value) in D:\a\Vortice.Win32\Vortice.Win32\src\Vortice.Win32.Graphics.Direct2D\ID2D1Properties.cs:line 257
```

**Comment by amerkoleci** [comment]
Call SetEnumValue

**Comment by RoccoZero** [comment]
i can't use SetEnumValue
I need SetValue because that's where I send the matrix
I get an error if I use SetValue and the first parameter index is Enum
<img width="730" alt="image" src="https://github.com/amerkoleci/Vortice.Win32/assets/33149580/70ece5f3-4272-43d7-a02e-8a07af40ba1c">

**Comment by amerkoleci** [comment]
Then use SetValue and pass the Matrix3x2, without the &translation, just use translation

**Comment by RoccoZero** [comment]
this working SetValue((uint)AffineTransform2DProperties.TransformMatrix, translation);

but why can’t I remove enum cast to uint? It worked before
(uint)AffineTransform2DProperties.TransformMatrix

**Comment by RoccoZero** [comment]
C++ looks like this, no need to cast

<img width="462" alt="image" src="https://github.com/amerkoleci/Vortice.Win32/assets/33149580/e8b08e2c-22f3-4b1e-ac69-81e32854e9d3">

**Comment by amerkoleci** [comment]
C# enums are different from C++ one

**Comment by RoccoZero** [comment]
I think that you have some kind of problem here, I don’t see any difference here
this SetEnumValue is not needed

<img width="1187" alt="image" src="https://github.com/amerkoleci/Vortice.Win32/assets/33149580/1382cb79-5700-482e-9acb-3b76adbd83aa">

**Comment by amerkoleci** [comment]
Send PR, thanks!

**Comment by RoccoZero** [comment]
I found another mistake, you don't use ": uint"
![image](https://github.com/amerkoleci/Vortice.Win32/assets/33149580/f7342eae-324d-4bc7-85a2-a409fed221a2)

because of this, this code of yours is useless for the enum type
it gives this error System.InvalidCastException: Unable to cast object of type 'Win32.Graphics.Direct2D.AffineTransform2DProperties' to type 'System.UInt32'.
![image](https://github.com/amerkoleci/Vortice.Win32/assets/33149580/b04805cd-b9b0-4782-8f30-ad62aca9f944)

this is how it was on the old version
![image](https://github.com/amerkoleci/Vortice.Win32/assets/33149580/78e15dde-d26c-4616-94a2-15333d284063)
